# See https://rust-lang.github.io/rustup/overrides.html for details on how this file works
# and how you can override the choices made herein.
#
# Note that we UniFFI also sets their own toolchain (see https://github.com/mozilla/uniffi-rs/blob/main/rust-toolchain.toml).
# We will attempt to track stable unless we find that this breaks something.
# The iOS targets are easy and well-known, but the Android targets take a bit more work to deduce.
# We have drawn our list from https://github.com/mozilla/rust-android-gradle.

[toolchain]
channel = "stable"
targets = [
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",

    # Android
    "armv7-linux-androideabi",
    "i686-linux-android",
    "aarch64-linux-android",
    "x86_64-linux-android",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
]
components = ["clippy", "rustfmt"]
