// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "ubrn-bug-reproducer.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNUbrnBugReproducerSpec.h"

@interface UbrnBugReproducer : NSObject <NativeUbrnBugReproducerSpec>
#else
#import <React/RCTBridgeModule.h>

@interface UbrnBugReproducer : NSObject <RCTBridgeModule>
#endif

@end